-- MzikTV Tickets — Supabase schema
-- Run this once in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- The backend talks to these tables with the service-role key, which bypasses
-- Row Level Security. RLS is enabled with NO policies so that the public/anon
-- key can never read guest data even if it leaks.

create table if not exists guests (
  id text primary key,
  full_name text not null,
  normalized_name text not null,
  gender text not null,
  access_code text not null,
  event_slug text not null,
  ticket_type_id text not null,
  invite_label text not null,
  source text not null default 'admin',
  password_hash text not null,
  created_at timestamptz not null default now(),
  checked_in_at timestamptz
);

-- One guest per (name, internal access key). The key is generated by the backend
-- and is not shown in the webapp.
create unique index if not exists guests_name_code_idx
  on guests (normalized_name, access_code);

create table if not exists tickets (
  id text primary key,
  guest_id text not null references guests (id) on delete cascade,
  event_id text not null,
  issued_at timestamptz not null default now(),
  checked_in_at timestamptz,
  token_hash text,
  token_version integer not null default 2
);

create index if not exists tickets_guest_idx on tickets (guest_id);
create unique index if not exists tickets_guest_event_idx on tickets (guest_id, event_id);

create table if not exists checkins (
  id text primary key,
  ticket_id text not null,
  guest_id text not null references guests (id) on delete cascade,
  event_id text not null,
  checked_in_at timestamptz not null default now()
);

create index if not exists checkins_guest_idx on checkins (guest_id);
create unique index if not exists checkins_ticket_idx on checkins (ticket_id);
create unique index if not exists checkins_guest_event_idx on checkins (guest_id, event_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'checkins_ticket_id_fkey'
  ) then
    alter table checkins
      add constraint checkins_ticket_id_fkey
      foreign key (ticket_id) references tickets (id) on delete cascade;
  end if;
end $$;

create or replace function check_in_ticket_atomic(
  p_ticket_id text,
  p_token_hash text,
  p_checkin_id text,
  p_checked_in_at timestamptz
)
returns table (
  ticket_id text,
  guest_id text,
  event_id text,
  checked_in_at timestamptz,
  already_checked_in boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ticket tickets%rowtype;
  v_guest guests%rowtype;
begin
  select *
    into v_ticket
    from tickets
    where id = p_ticket_id
      and token_hash = p_token_hash
    for update;

  if not found then
    return;
  end if;

  select *
    into v_guest
    from guests
    where id = v_ticket.guest_id
    for update;

  if not found then
    return;
  end if;

  if v_ticket.checked_in_at is not null or v_guest.checked_in_at is not null then
    return query
      select v_ticket.id, v_ticket.guest_id, v_ticket.event_id, coalesce(v_ticket.checked_in_at, v_guest.checked_in_at), true;
    return;
  end if;

  update tickets
    set checked_in_at = p_checked_in_at
    where id = v_ticket.id;

  update guests
    set checked_in_at = p_checked_in_at
    where id = v_ticket.guest_id;

  insert into checkins (id, ticket_id, guest_id, event_id, checked_in_at)
    values (p_checkin_id, v_ticket.id, v_ticket.guest_id, v_ticket.event_id, p_checked_in_at);

  return query
    select v_ticket.id, v_ticket.guest_id, v_ticket.event_id, p_checked_in_at, false;
end;
$$;

-- Lock the tables down to the service role only.
alter table guests enable row level security;
alter table tickets enable row level security;
alter table checkins enable row level security;
